### ISSUE TITLE
Make it possible to run on devices with 6" display

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/launcher#39]
Make the layout responsive to a variety of display widths/height/DPIs.

- [x] Landscape orientation
- [x] Portrait orientation

Consider using a completely different layout (e.g. vertical) when the device is in portrait orientation?

---

6" landscape mode:

![device-2020-06-10-163717](https://user-images.githubusercontent.com/15718174/84246356-190d2980-ab39-11ea-8c25-773f6f911fe7.png)

![device-2020-06-10-163823](https://user-images.githubusercontent.com/15718174/84246368-1dd1dd80-ab39-11ea-9ca7-ea8def0c4969.png)

6" portrait mode:

![device-2020-06-10-163953](https://user-images.githubusercontent.com/15718174/84246458-3c37d900-ab39-11ea-804c-02740074867d.png)

![device-2020-06-10-164009](https://user-images.githubusercontent.com/15718174/84246471-40fc8d00-ab39-11ea-91ba-3712e0622590.png)

**Comment by gscdev** [comment]
Do you think this is a good distribution for portrait orientation?

![device-2020-06-24-002301](https://user-images.githubusercontent.com/8291318/85471754-33bbb580-b5b1-11ea-8781-4ffbdb41c6bd.png)

**Comment by nya-elimuai** [comment]
> Do you think this is a good distribution for portrait orientation?

@gscdev Yes, this looks great, thank you!

Could you add the code changes to a branch or a pull request at https://github.com/elimu-ai/launcher so that I can test the changes?
